### ISSUE TITLE
DNA Folding framework discussion

### ISSUE THREAD

**Issue by shanilpanara** [shanilpanara/origamiUROP#18]
# Summary
We currently haven't discussed in any depth about how we might go about folding the DNA strand in detail. So hopefully we can throw some ideas around and brainstorm on this issue before we reach the stage of implementing this

# My thoughts
We might need the following steps/methods (this is essentially my logic)
1. A method of finding all the points (for a given resolution) which lie within the  `BoundaryPolygon` or alternatively a method to check whether a point **lies within the bounds** of `BoundaryPolygon`
    - I have a feeling _shapely_ has a method of doing this, we could either use shapely or copy part of their algorithm for this
2. Choose the **mode of folding** -> to begin I think we simplify the task by choosing either horizontal folding or vertical folding within the 'BoundaryPolygon'
3. Define a **grid** (based on this mode of folding) which has rows (or columns - for the vertical folding mode) constrained in length (a specific no. of bases) which allows for folding such that we follow the rules of DNA origami, e.g.: 
    - we are only permitted an **integer no. of turns** - this will depend on the twist angle per base, but we could use the convention as set out in the paper (16 bases per 1.5 turns, i.e. 540 degrees)
        - So I think essentially only multiples of 32 bases are allowed 
    - an **even no. of parallel double helices**
    - crossovers can only occur at any **odd no. of a half turns** since the last fold/beginning, i.e. 0.5,1.5,2.5, such that the helix stays in plane
    - top/bottom edge (for horizontal folding) and left/right edge (for vertical folding) require **an even no. of turns**
        - So a multiple of 64 bases
4. Algorithm of generating scaffold layouts (hopefully using the above grid)
5. Converting each fold of the scaffold into `Edge` objects which we can use to define `dir` when creating the oxDNA representation -> I envision we'll need a new class, `Scaffold`, which is a collection of `Edge` objects with the `Edge.kind = 'scaffold'`
    - This is the point at which we can program in the interhelix gap spacing, using emperical values, as used in the rothermund paper, e.g. 1.5 turns crossover = 1nm, 2.5 turns crossover = 1.5nm
6. Finally a method to convert the `Scaffold` object into a DNA `System`

![image](https://user-images.githubusercontent.com/67636677/87666093-ea015d80-c75f-11ea-84dc-f297731b2705.png)
_From the Rothermund paper_

**Comment by debeshmandal** [comment]
I like your thinking but there are a few things that you need to understand before jumping into this, and in fact I think once we complete the other issues, it will be beneficial to 'take a week off' and tidy up existing code, and give you time to research a few things.

Some background before getting stuck into the problem:
  - Reduced units for simulations (definitely worth asking Stefano about this)
  - [Travelling salesman class of computation problems](https://en.wikipedia.org/wiki/Travelling_salesman_problem)
  - [Making angles with origami](https://advances.sciencemag.org/content/5/1/eaav0655)
  - [point in polygon class of computation problems](https://en.wikipedia.org/wiki/Point_in_polygon)
  - [Rasterisation Algorithms](https://www.scratchapixel.com/lessons/3d-basic-rendering/rasterization-practical-implementation)

Here are some of my thoughts:

### Describing a lattice within a Polygon

You are correct in saying that we need to create a grid that the scaffold needs to follow. We will call this a lattice. There is a lot of potential for creating a 2D lattice filling algorithm, and we can take into account some of these features:

  - preferred angle based on the length of the two sides forming it
  - using single-helix portions to improve/make worse angle stability (like PERDIX paper)
  - different paths for the scaffold (this has huge potential and we will have to start simple and then become more complex later)

### Rules for the DNA

We can be a bit creative with how we fill the lattice. This is where I'm not 100% sure on how we will achieve multiple solutions to the travelling salesman problem. Basically we have to describe our constraints to the problem e.g. all points on the lattice must be filled, a DNA segment must have a certain length etc. We also need to think about the architecture we will use to describe the lattice. We can potentially create some new classes, but again I'm not sure exactly how we'll do this. An important note is that we will be using the oxDNA units system, which I don't know off the top of my head, so you need to read up on using reduced units to understand how this works.

### Rasterisation

I think the rasterisation method is a good one to follow - PERDIX also offers a different class of algorithm which would actually be simpler (I think - again could be wrong). There are a huge number (although not infinitely large) of ways to raster a single polygon. We can be creative here and I think it would be good to create a presentation summarising different methods before we try and do it. (we can use the sandbox to experiment)

I need to think a bit more about how we can achieve this all in smart way in terms of architecture (as you can probably tell, I'm a bit shaky on some of the details). Most importantly, our filling algorithms all must take the same form (potentially a low level class called `RasterAlgorithm` from which they all inherit could work) and we need to make it so that new algorithms can be added easily.

**Comment by shanilpanara** [comment]
@debeshmandal have nearly finished preparing a doc to present at tomorrows meeting RE: rasterisation or "routing" algorithm for the scaffold

**Comment by debeshmandal** [comment]
I'm going to look at creating a new set of classes called:

- `RasterNode` equivalent of `Vertex` but for rasterisation and defining Lattice sites
- `RasterEdge` equivalent to `Edge` but again for rasterisation and making a path between Lattice sites
- `RasterLattice` - lattice inside a 2D polygon which collects the `Raster*` objects and inherits from `oxdna.System`
- 'abstract class' `DNANode` which `Vertex` and `RasterNode` will inherit from (note that these may end up being unnecessary)
- 'abstract class' `DNAPath` which `Edge` and `RasterEdge` will inherit from
- The `DNA*` classes will allow us to draw oxDNA strands along `Edge` and `RasterEdge` objects

I think this will be quite effective, but also a bit complicated so I will make a draft in a separate branch and we can see what it looks like and discuss later.
